In [1]:
def my_function():
    pass

In [2]:
def my_sq(x):
    return x ** 2

In [3]:
my_sq(4)

16

In [4]:
def avg_2(x, y):
    return (x + y) / 2

In [5]:
avg_2(10, 20)

15.0

In [8]:
assert avg_2(10, 20) == 15.0

In [9]:
import pandas as pd

In [10]:
df=pd.DataFrame({'a':[10,20,30],
                 'b':[20,30,40]})
df

a   b
0  10  20
1  20  30
2  30  40

In [11]:
df['a'] ** 2

0    100
1    400
2    900
Name: a, dtype: int64

In [12]:
type(df['a'])

pandas.core.series.Series

In [13]:
def my_sq(x):
    # assert isinstance(x, int)
    return x ** 2

In [14]:
df['a'].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [15]:
def my_exp(x, e):
    return x ** e

In [16]:
my_exp(2, 2)

4

In [17]:
my_exp(2, 10)

1024

In [18]:
df['a'].apply(my_exp, e=10)

0        10000000000
1     10240000000000
2    590490000000000
Name: a, dtype: int64

In [19]:
def print_me(x):
    print(x)

In [20]:
print_me('hello')

hello


In [21]:
df

a   b
0  10  20
1  20  30
2  30  40

In [22]:
df.apply(print_me, axis=0)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [23]:
def avg_3(x, y, z):
    return (x + y + z) / 3

In [24]:
avg_3(0, 5, 10)

5.0

In [25]:
df.apply(avg_3)

TypeError: ("avg_3() missing 2 required positional arguments: 'y' and 'z'", 'occurred at index a')

In [30]:
import numpy as np
def avg_3_apply(col):
    # return np.sum(col) / 3
    return np.mean(col)

In [31]:
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x + y + z) / 3

In [32]:
df

a   b
0  10  20
1  20  30
2  30  40

In [33]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [34]:
df.apply(avg_3_apply, axis=1)

IndexError: ('index out of bounds', 'occurred at index 0')

In [35]:
def avg_2_apply(row):
    x = row[0]
    y = row[1]
    return (x + y) / 2

In [36]:
df.apply(avg_2_apply, axis=1)

0    15.0
1    25.0
2    35.0
dtype: float64

In [37]:
import seaborn as sns

In [38]:
titanic = sns.load_dataset('titanic')

In [39]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [41]:
import numpy as np

def count_missing(vec):
    """Counts the number of missing values in a vector
    """
    null_vec = pd.isnull(vec)
    null_count = np.sum(null_vec)
    return null_count

In [42]:
count_missing?

In [43]:
cmis_col = titanic.apply(count_missing)

In [44]:
cmis_col

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [45]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
survived       891 non-null int64
pclass         891 non-null int64
sex            891 non-null object
age            714 non-null float64
sibsp          891 non-null int64
parch          891 non-null int64
fare           891 non-null float64
embarked       889 non-null object
class          891 non-null category
who            891 non-null object
adult_male     891 non-null bool
deck           203 non-null category
embark_town    889 non-null object
alive          891 non-null object
alone          891 non-null bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


In [51]:
cmiss_row = titanic.apply(count_missing, axis=1)
cmiss_row

0      1
1      0
2      1
3      0
4      1
5      2
6      0
7      1
8      1
9      1
10     0
11     0
12     1
13     1
14     1
15     1
16     1
17     2
18     1
19     2
20     1
21     0
22     1
23     0
24     1
25     1
26     2
27     0
28     2
29     2
      ..
861    1
862    0
863    2
864    1
865    1
866    1
867    0
868    2
869    1
870    1
871    0
872    0
873    1
874    1
875    1
876    1
877    1
878    2
879    0
880    1
881    1
882    1
883    1
884    1
885    1
886    1
887    0
888    2
889    0
890    1
Length: 891, dtype: int64

In [52]:
cmiss_row.value_counts()

1    549
0    182
2    160
dtype: int64

In [58]:
def avg_2(x, y):
    return (x + y) / 2

In [59]:
df

a   b
0  10  20
1  20  30
2  30  40

In [56]:
(df['a'] + df['b']) / 2

0    15.0
1    25.0
2    35.0
dtype: float64

In [60]:
def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [61]:
avg_2(df['a'], df['b'])

0    15.0
1    25.0
2    35.0
dtype: float64

In [62]:
avg_2_mod(df['a'], df['b'])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [65]:
(df['a'] == 20)

0    False
1     True
2    False
Name: a, dtype: bool

In [66]:
(df['a'] == 20).any()

True

In [68]:
avg_2_mod(10, 20)

15.0

In [69]:
avg_2_mod(20, 30)

nan

In [70]:
import numpy as np

In [71]:
avg_2_mod_vec = np.vectorize(avg_2_mod)

In [72]:
avg_2_mod_vec(df['a'], df['b'])

array([15., nan, 35.])

In [74]:
@np.vectorize
def v_avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [75]:
v_avg_2_mod(df['a'], df['b'])

array([15., nan, 35.])

In [76]:
import numba

In [77]:
@numba.vectorize
def v_avg_2_mod_numba(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [78]:
v_avg_2_mod_numba(df['a'], df['b'])

ValueError: cannot determine Numba type of <class 'pandas.core.series.Series'>

In [79]:
v_avg_2_mod_numba(df['a'].values, df['b'].values)

array([15., nan, 35.])

In [80]:
%%timeit
avg_2(df['a'], df['b'])

557 µs ± 49.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [81]:
%%timeit
v_avg_2_mod(df['a'], df['b'])

136 µs ± 4.68 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [84]:
%%timeit
v_avg_2_mod_numba(df['a'].values, df['b'].values)

17.5 µs ± 992 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
